const allStocks = [
  {
    id: 1,
    img: "/img/products/bomboane1.jpg",
    name: "Raffaelo",
    producator: "Ferrero SpA",
    data: "01-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 200,
    pretTotCump: 6800,
    pretTotVinz: 10000,
    state: "in sale",
  },
  {
    id: 2,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "07-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 3,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "07-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 4,
    img: "/img/products/bomboane1.jpg",
    name: "Raffaelo",
    data: "01-07-2020",
    producator: "Ferrero SpA",
    data: "17-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 300,
    pretTotCump: 7200,
    pretTotVinz: 15000,
    state: "in waiting",
  },
  {
    id: 5,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "21-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 400,
    pretTotCump: 13600,
    pretTotVinz: 20000,
    state: "in waiting",
  },
  {
    id: 6,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "01-08-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 7,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "01-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 200,
    pretTotCump: 6800,
    pretTotVinz: 10000,
    state: "in sale",
  },
  {
    id: 8,
    img: "/img/products/bomboane1.jpg",
    name: "Raffaelo",
    data: "01-07-2020",
    producator: "Ferrero SpA",
    data: "07-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 9,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    producator: "AVICOLA floreni",
    data: "07-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 10,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "17-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 300,
    pretTotCump: 7200,
    pretTotVinz: 15000,
    state: "in waiting",
  },
  {
    id: 11,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "21-07-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 400,
    pretTotCump: 13600,
    pretTotVinz: 20000,
    state: "in waiting",
  },
  {
    id: 12,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "01-08-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 13,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "01-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 200,
    pretTotCump: 6800,
    pretTotVinz: 10000,
    state: "in sale",
  },
  {
    id: 14,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    producator: "S.A. Bucuria",
    data: "02-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 15,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    producator: "AVICOLA floreni",
    data: "03-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 16,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "17-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 300,
    pretTotCump: 7200,
    pretTotVinz: 15000,
    state: "in waiting",
  },
  {
    id: 17,
    img: "/img/products/carne3.jpg",
    name: "Tacîm pentru felul întîi",
    producator: "AVICOLA floreni",
    data: "21-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 400,
    pretTotCump: 13600,
    pretTotVinz: 20000,
    state: "in waiting",
  },
  {
    id: 18,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    producator: "AXEDUM",
    data: "01-08-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 19,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    producator: "AVICOLA floreni",
    data: "01-09-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 200,
    pretTotCump: 6800,
    pretTotVinz: 10000,
    state: "in sale",
  },
  {
    id: 20,
    img: "/img/products/carne3.jpg",
    name: "Tacîm pentru felul întîi",
    producator: "AVICOLA floreni",
    data: "17-10-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 21,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    producator: "AVICOLA floreni",
    data: "08-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 22,
    img: "/img/products/fructe3.jpeg",
    name: "Poamă",
    producator: "S.A Tighina",
    data: "11-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 300,
    pretTotCump: 7200,
    pretTotVinz: 15000,
    state: "in waiting",
  },
  {
    id: 23,
    img: "/img/products/carne3.jpg",
    name: "Tacîm pentru felul întîi",
    producator: "AVICOLA floreni",
    data: "20-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 400,
    pretTotCump: 13600,
    pretTotVinz: 20000,
    state: "in waiting",
  },
  {
    id: 24,
    img: "/img/products/fructe1.jpeg",
    name: "Pepene verde",
    producator: "S.A Tighina",
    data: "21-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 25,
    img: "/img/products/fructe2.jpeg",
    name: "Nectarine",
    producator: "S.A Tighina",
    data: "23-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 26,
    img: "/img/products/fructe1.jpeg",
    name: "Pepene verde",
    producator: "S.A Tighina",
    data: "25-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 27,
    img: "/img/products/fructe3.jpeg",
    name: "Poamă",
    producator: "S.A Tighina",
    data: "25-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 28,
    img: "/img/products/fructe1.jpeg",
    name: "Pepene verde",
    producator: "S.A Tighina",
    data: "25-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 29,
    img: "/img/products/fructe2.jpeg",
    name: "Nectarine",
    producator: "S.A Tighina",
    data: "26-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
  {
    id: 30,
    img: "/img/products/iaurt1.jpg",
    name: "Activia",
    producator: "Danone",
    data: "26-11-2020",
    pretCump: 34,
    pretVinz: 50,
    cantitate: 100,
    pretTotCump: 3400,
    pretTotVinz: 5000,
    state: "in waiting",
  },
];
export default allStocks;
