const data = [
  {
    id: 1,
    img: "/img/operators/operator1.jpg",
    nickname: "jhon",
    name: "Ion",
    surname: "Petrescu",
    email: "ion@mail.com",
    tel: "068765445",
    status: "activ",
  },
  {
    id: 2,
    img: "/img/operators/operator2.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 3,
    img: "/img/operators/operator3.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 4,
    img: "/img/operators/operator4.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 5,
    img: "/img/operators/operator5.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 6,
    img: "/img/operators/operator1.jpg",
    nickname: "jhon",
    name: "Ion",
    surname: "Petrescu",
    email: "ion@mail.com",
    tel: "068765445",
    status: "activ",
  },
  {
    id: 7,
    img: "/img/operators/operator2.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 8,
    img: "/img/operators/operator3.jpg",
    nickname: "poka",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 9,
    img: "/img/operators/operator4.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 10,
    img: "/img/operators/operator5.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 11,
    img: "/img/operators/operator1.jpg",
    nickname: "jhon",
    name: "Ion",
    surname: "Petrescu",
    email: "ion@mail.com",
    tel: "068765445",
    status: "activ",
  },
  {
    id: 12,
    img: "/img/operators/operator2.jpg",
    nickname: "op2",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 13,
    img: "/img/operators/operator3.jpg",
    nickname: "op3",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 14,
    img: "/img/operators/operator4.jpg",
    nickname: "op4",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 15,
    img: "/img/operators/operator5.jpg",
    nickname: "op5",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 16,
    img: "/img/operators/operator1.jpg",
    nickname: "jhon",
    name: "Ion",
    surname: "Petrescu",
    email: "ion@mail.com",
    tel: "068765445",
    status: "activ",
  },
  {
    id: 17,
    img: "/img/operators/operator2.jpg",
    nickname: "nik",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 18,
    img: "/img/operators/operator3.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 19,
    img: "/img/operators/operator4.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
  {
    id: 20,
    img: "/img/operators/operator5.jpg",
    nickname: "op1",
    name: "Mihail",
    surname: "Ponta",
    email: "ponta@mail.com",
    tel: "06879643",
    status: "inactiv",
  },
];
export default data;
