export const category = [
  "Băcănie",
  "Dulciuri",
  "Carne",
  "Lactate și brânzeturi",
  "Fructe și legume",
  "Mezeluri",
  "Pește",
  "Ouă",
  "Panificație",
  "Băuturi nealcoolice",
  "Băuturi alcoolice",
];
export const subcategory = [
  "Ulei",
  "Condimente",
  "Paste",
  "Sare",
  "Zahăr",
  "Făină",
  "Fulgi de ovaz",
  "Crupe",
  "Bomboane",
  "Ciocolată",
  "Biscuiți",
  "Croissante",
  "Napolitane",
  "Carne de pui",
  "Carne de porc",
  "Carne tocată",
  "Chefir",
  "Lapte",
  "Cașcaval",
  "Brânză",
  "Iaurt",
  "Smîntînă",
  "Brânză topită",
  "Cremă de brânză",
  "Fructe",
  "Legume",
  "Parizieri",
  "Crenvuști",
  "Cîrnaț",
  "Șuncă",
  "Pește sărat",
  "Pește uscat",
  "Pâine",
  "Patiserie",
  "Ceai",
  "Cafea",
  "Apă minerală",
  "Energizant",
  "Vin",
  "Vin spumant",
  "Spirtoase",
  "Bere",
];
export const unitate = ["bucați", "kg"];
export const producatori = [
  "Ferrero SpA",
  "S.A. Bucuria",
  "AXEDUM",
  "AVICOLA floreni",
  "S.A Tighina",
  "Danone",
  "ProdLacta",
  "latti",
  "JLK",
  "Căsuța mea",
  "Ferma",
  "Zi de zi",
  "Rogob",
  "Carmez",
  "Domnița",
  "Moș Zaharia",
];
export const productFields = {
  category,
  subcategory,
  unitate,
  producatori,
};
// export default productFields;
