const productsData = [
  {
    id: 1,
    img: "/img/products/bomboane1.jpg",
    name: "Raffaelo",
    categorie: "Dulciuri",
    subcategorie: "Bomboane",
    producator: "Ferrero SpA",
    cantitate: 657,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 2,
    img: "/img/products/bomboane2.jpg",
    name: "Clepsidra",
    categorie: "Dulciuri",
    subcategorie: "Bomboane",
    producator: "S.A. Bucuria",
    cantitate: 234,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 3,
    img: "/img/products/bomboane3.jpg",
    name: "Clepsidra Cafea",
    categorie: "Dulciuri",
    subcategorie: "Bomboane",
    producator: "S.A. Bucuria",
    cantitate: 108,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 4,
    img: "/img/products/carne1.jpg",
    name: "Piept de pui cu os",
    categorie: "Carne",
    subcategorie: "Carne de pui",
    producator: "AXEDUM",
    cantitate: 88,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 5,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    categorie: "Carne",
    subcategorie: "Carne de pui",
    producator: "AVICOLA floreni",
    cantitate: 110,
    unitate: "bucați",
    pret: 24,
  },
  {
    id: 6,
    img: "/img/products/carne2.jpg",
    name: "Gamba de pui",
    categorie: "Carne",
    subcategorie: "Carne de pui",
    producator: "AVICOLA floreni",
    cantitate: 110,
    unitate: "bucați",
    pret: 24,
  },
  {
    id: 7,
    img: "/img/products/carne3.jpg",
    name: "Tacîm pentru felul întîi",
    categorie: "Carne",
    subcategorie: "Carne de pui",
    producator: "AVICOLA floreni",
    cantitate: 210,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 8,
    img: "/img/products/carne3.jpg",
    name: "Tacîm pentru felul întîi",
    categorie: "Carne",
    subcategorie: "Carne de pui",
    producator: "AVICOLA floreni",
    cantitate: 210,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 9,
    img: "/img/products/fructe1.jpeg",
    name: "Pepene verde",
    categorie: "Fructe și legume",
    subcategorie: "Fructe",
    producator: "S.A Tighina",
    cantitate: 34,
    unitate: "kg",
    pret: 16,
  },
  {
    id: 10,
    img: "/img/products/fructe2.jpeg",
    name: "Nectarine",
    categorie: "Fructe și legume",
    subcategorie: "Fructe",
    producator: "S.A Tighina",
    cantitate: 44,
    unitate: "kg",
    pret: 23,
  },
  {
    id: 11,
    img: "/img/products/fructe3.jpeg",
    name: "Poamă",
    categorie: "Fructe și legume",
    subcategorie: "Fructe",
    producator: "S.A Tighina",
    cantitate: 41,
    unitate: "kg",
    pret: 19,
  },
  {
    id: 12,
    img: "/img/products/iaurt1.jpg",
    name: "Activia",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Iaurt",
    producator: "Danone",
    cantitate: 180,
    unitate: "bucați",
    pret: 9,
  },
  {
    id: 13,
    img: "/img/products/iaurt2.jpg",
    name: "Activia cereale",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Iaurt",
    producator: "Danone",
    cantitate: 110,
    unitate: "bucați",
    pret: 11,
  },
  {
    id: 14,
    img: "/img/products/iaurt3.jpg",
    name: "Danonino",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Iaurt",
    producator: "Danone",
    cantitate: 70,
    unitate: "bucați",
    pret: 13,
  },
  {
    id: 15,
    img: "/img/products/iaurt4.jpg",
    name: "Danonino banane",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Iaurt",
    producator: "Danone",
    cantitate: 67,
    unitate: "bucați",
    pret: 14,
  },
  {
    id: 16,
    img: "/img/products/lapte1.jpg",
    name: "Lapte de munte",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "ProdLacta",
    cantitate: 34,
    unitate: "bucați",
    pret: 16,
  },
  {
    id: 17,
    img: "/img/products/lapte2.jpg",
    name: "Lapte1L 2.0%",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "latti",
    cantitate: 30,
    unitate: "bucați",
    pret: 16,
  },
  {
    id: 18,
    img: "/img/products/lapte3.jpg",
    name: "Lapte1L 2.5%",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "JLK",
    cantitate: 32,
    unitate: "bucați",
    pret: 17,
  },
  {
    id: 19,
    img: "/img/products/lapte4.jpg",
    name: "Lapte1L 6%",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "Căsuța mea",
    cantitate: 17,
    unitate: "bucați",
    pret: 19,
  },
  {
    id: 20,
    img: "/img/products/lapte5.jpg",
    name: "Lapte1L 2.5%",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "JLK",
    cantitate: 27,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 21,
    img: "/img/products/lapte6.jpg",
    name: "Lapte de la fermă 1L 2.5%",
    categorie: "Lactate și brânzeturi",
    subcategorie: "Lapte",
    producator: "Ferma",
    cantitate: 20,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 22,
    img: "/img/products/mezeluri1.jpg",
    name: "Cabanos A",
    categorie: "Mezeluri",
    subcategorie: "Parizieri",
    producator: "Zi de zi",
    cantitate: 34,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 23,
    img: "/img/products/mezeluri2.jpg",
    name: "Servelat de Chișinău",
    categorie: "Mezeluri",
    subcategorie: "Parizieri",
    producator: "Rogob",
    cantitate: 23,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 24,
    img: "/img/products/mezeluri3.jpg",
    name: "Servelat țărănesc",
    categorie: "Mezeluri",
    subcategorie: "Parizieri",
    producator: "Carmez",
    cantitate: 21,
    unitate: "bucați",
    pret: 27,
  },
  {
    id: 25,
    img: "/img/products/zahar1.jpg",
    name: "Zahăr pudră",
    categorie: "Băcănie",
    subcategorie: "Zahăr",
    producator: "Domnița",
    cantitate: 121,
    unitate: "bucați",
    pret: 20,
  },
  {
    id: 26,
    img: "/img/products/zahar2.jpg",
    name: "Zahăr brun",
    categorie: "Băcănie",
    subcategorie: "Zahăr",
    producator: "Moș Zaharia",
    cantitate: 98,
    unitate: "bucați",
    pret: 23,
  },
  {
    id: 27,
    img: "/img/products/zahar3.jpg",
    name: "Zahăr cristal",
    categorie: "Băcănie",
    subcategorie: "Zahăr",
    producator: "Moș Zaharia",
    cantitate: 45,
    unitate: "bucați",
    pret: 19,
  },
];
export default productsData;
